"""
ALICE_CoPilot Search Handler.
Provides async integration with ALICE_Search CLI and clean Discord Embed generation.
Ensures strict memory ownership guard: CoPilot only accesses jobs belonging to the authorized owner.
"""
import asyncio
import json
import logging
import re
from pathlib import Path
from typing import Any
import discord
import config

logger = logging.getLogger("ALICE_CoPilot.Search")

SEARCH_PYTHON_BIN = "/home/takuya/Project_ALICE/myenv/core_env/bin/python"
SEARCH_CLI_PATH = "/home/takuya/Project_ALICE/ALICE_Search/cli.py"


def clean_html_snippet(snippet: str) -> str:
    """HTML tags like <b>...</b> generated by FTS5 snippet to Discord markdown **...**."""
    if not snippet:
        return ""
    # Replace <b> and </b> with **
    text = re.sub(r"</?b>", "**", snippet)
    # Remove any other unexpected HTML tags
    text = re.sub(r"<[^>]+>", "", text)
    # Normalize multiple newlines
    text = re.sub(r"\n{2,}", "\n", text).strip()
    return text


async def execute_search(
    query: str,
    limit: int = 5,
    user_id: str | None = None,
    module: str | None = None,
    python_bin: str = SEARCH_PYTHON_BIN,
    cli_path: str = SEARCH_CLI_PATH,
) -> dict[str, Any]:
    """Execute ALICE_Search CLI asynchronously and return parsed JSON."""
    if not query.strip():
        return {"total": 0, "query": query, "hits": [], "error": "検索キーワードが空です"}

    cmd = [
        python_bin,
        cli_path,
        "--query",
        query.strip(),
        "--limit",
        str(limit),
    ]
    if user_id:
        cmd.extend(["--user", user_id])
    if module:
        cmd.extend(["--module", module])

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=15.0)

        if proc.returncode != 0:
            err_msg = stderr.decode("utf-8", errors="replace").strip()
            logger.error(f"[SearchHandler] CLI failed (code={proc.returncode}): {err_msg}")
            return {"total": 0, "query": query, "hits": [], "error": err_msg}

        data = json.loads(stdout.decode("utf-8"))
        return data

    except asyncio.TimeoutError:
        logger.error(f"[SearchHandler] Query timed out: {query}")
        return {"total": 0, "query": query, "hits": [], "error": "検索処理がタイムアウトしました"}
    except Exception as e:
        logger.error(f"[SearchHandler] Execution error: {e}")
        return {"total": 0, "query": query, "hits": [], "error": str(e)}


def build_search_embed(result: dict[str, Any], query: str) -> discord.Embed:
    """Build a clean, readable Discord Embed from search results without noisy emojis."""
    error = result.get("error")
    if error:
        embed = discord.Embed(
            title=f"検索エラー: {query}",
            description=f"検索の実行中にエラーが発生しました。\n`{error}`",
            color=0xE74C3C,  # Soft Red
        )
        embed.set_footer(text="ALICE Knowledge & Search v1.0")
        return embed

    total = result.get("total", 0)
    hits = result.get("hits", [])

    if total == 0 or not hits:
        embed = discord.Embed(
            title=f"検索結果: {query}",
            description="該当する過去の会話・要約は見つかりませんでした。\n検索条件を変更してお試しください。",
            color=0x7F8C8D,  # Slate Grey
        )
        embed.set_footer(text="ALICE Knowledge & Search v1.0")
        return embed

    display_count = min(len(hits), 5)
    embed = discord.Embed(
        title=f"検索結果: {query}",
        description=f"一致件数: {total} 件 (上位 {display_count} 件を表示)",
        color=0x2980B9,  # Calm Blue
    )

    displayed_count = 0
    for hit in hits:
        job_id = hit.get("job_id", "unknown")
        meta = hit.get("metadata", {})
        original_filename = meta.get("original_filename") or job_id
        module = hit.get("module", "unknown")
        created_at_raw = hit.get("created_at", "")
        created_str = created_at_raw[:16].replace("T", " ") if created_at_raw else "日時不明"

        raw_snippet = hit.get("snippet", "")
        clean_snippet = clean_html_snippet(raw_snippet)
        if len(clean_snippet) > 250:
            clean_snippet = clean_snippet[:247] + "..."

        # Quote block for snippet to make it clean and readable
        quoted_snippet = "\n".join(f"> {line}" for line in clean_snippet.splitlines())

        field_title = f"{original_filename} [{module.upper()}]"
        field_value = (
            f"日時: `{created_str}` | Job: `{job_id}`\n"
            f"{quoted_snippet}"
        )

        embed.add_field(name=field_title, value=field_value, inline=False)
        displayed_count += 1
        if displayed_count >= 5:
            break

    embed.set_footer(text="ALICE Knowledge & Search v1.0 | #search")
    return embed


def is_search_request(message: discord.Message) -> tuple[bool, str]:
    """Check if message is a search request.
    
    Returns:
        tuple[bool, str]: (is_search, search_query)
    """
    content = getattr(message, "content", "").strip()
    if not content:
        return False, ""

    channel = getattr(message, "channel", None)
    channel_name = getattr(channel, "name", "")

    # 1. 専用チャンネル #search の場合: 全文を検索クエリとして扱う
    if channel_name == "search":
        author = getattr(message, "author", None)
        if getattr(author, "bot", False):
            return False, ""
        return True, content

    # 2. 他チャンネルでのプレフィックスコマンド
    prefixes = ("!search ", "!s ", "検索: ", "検索 ")
    for p in prefixes:
        if content.startswith(p):
            query = content[len(p):].strip()
            return True, query

    return False, ""


async def handle_search_message(message: discord.Message) -> bool:
    """Handle message if it's a search request.
    
    Returns:
        bool: True if handled as search, False otherwise.
    """
    is_search, query = is_search_request(message)
    if not is_search:
        return False

    if not query:
        await message.channel.send("検索キーワードを指定してください。(例: `面談`, `!search 予算`)")
        return True

    try:
        # 記憶の防壁 (Contamination Guard):
        # CoPilotからの検索は常にオーナーの Core User ID (U794535d58fb802ac996f4a86ce119ad2) に強制限定する。
        # これにより、LINE等のゲストユーザーのJob成果物が検索結果に混入・漏洩することを100%遮断する。
        target_user_id = getattr(config, "OWNER_CORE_USER_ID", "U794535d58fb802ac996f4a86ce119ad2")
        if hasattr(message.channel, "typing"):
            async with message.channel.typing():
                result = await execute_search(query=query, limit=5, user_id=target_user_id)
        else:
            result = await execute_search(query=query, limit=5, user_id=target_user_id)
        embed = build_search_embed(result=result, query=query)
        await message.channel.send(embed=embed)
    except Exception as e:
        logger.error(f"[SearchHandler] Failed to handle search message: {e}")
        await message.channel.send(f"検索中にエラーが発生しました: {e}")

    return True
