import os
import sys
import shutil
import json
import subprocess
import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PYTHON_BIN = str(PROJECT_ROOT / "myenv" / "core_env" / "bin" / "python")
SUMMARY_CLI = str(PROJECT_ROOT / "ALICE_Summary" / "cli.py")


def get_available_real_transcript() -> Path | None:
    workspaces_dir = Path("/data/runtime/workspaces")
    if not workspaces_dir.exists():
        return None
    for ws in sorted(workspaces_dir.glob("job_*")):
        cand = ws / "transcript" / "transcript.json"
        if cand.exists() and cand.stat().st_size > 100:
            return cand
    return None


def test_missing_workspace(tmp_path):
    print("\n[Test 1] Missing workspace directory validation...")
    ws = tmp_path / "non_existent_workspace_xyz123"

    cmd = [PYTHON_BIN, SUMMARY_CLI, "--workspace", str(ws)]
    res = subprocess.run(cmd, capture_output=True, text=True)
    assert res.returncode != 0, f"Expected non-zero exit code, got {res.returncode}"
    print("Test 1 PASSED: Correctly failed on missing workspace.")


def test_missing_transcript(tmp_path):
    print("\n[Test 2] Missing transcript.json validation...")
    ws = tmp_path / "test_summary_no_transcript"
    ws.mkdir(parents=True, exist_ok=True)

    cmd = [PYTHON_BIN, SUMMARY_CLI, "--workspace", str(ws)]
    res = subprocess.run(cmd, capture_output=True, text=True)
    assert res.returncode != 0, f"Expected non-zero exit code, got {res.returncode}"
    print("Test 2 PASSED: Correctly failed on missing transcript.json.")


def test_pipeline_with_real_transcript(tmp_path):
    print("\n[Test 3] 3-Stage Pipeline execution with real transcript data...")
    source_transcript = get_available_real_transcript()
    if not source_transcript:
        pytest.skip("No authentic workspace transcript.json found for E2E test")

    print(f"Using source transcript: {source_transcript}")
    test_ws = tmp_path / "test_summary_pipeline_e2e"

    # ワークスペース初期化
    (test_ws / "transcript").mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_transcript, test_ws / "transcript" / "transcript.json")

    # Stage 1 + Stage 2 + Stage 3 実行
    cmd = [PYTHON_BIN, SUMMARY_CLI, "--workspace", str(test_ws), "--model", "gemma4:12b"]
    print(f"Running command: {' '.join(cmd)}")
    res = subprocess.run(cmd, capture_output=True, text=True)

    print(f"Stdout:\n{res.stdout}")
    if res.stderr:
        print(f"Stderr:\n{res.stderr}")
    assert res.returncode == 0, f"Pipeline failed with return code {res.returncode}"

    # 成果物の存在確認
    summary_dir = test_ws / "summary"
    analysis_file = summary_dir / "analysis.json"
    draft_file = summary_dir / "draft_summary.md"
    summary_md = summary_dir / "summary.md"
    summary_txt = summary_dir / "summary.txt"
    consistency_report = summary_dir / "consistency_report.md"
    metadata_file = summary_dir / "metadata.json"

    assert analysis_file.exists(), "analysis.json must exist"
    assert draft_file.exists(), "draft_summary.md must exist"
    assert summary_md.exists(), "summary.md must exist"
    assert summary_txt.exists(), "summary.txt must exist"
    assert consistency_report.exists(), "consistency_report.md must exist"
    assert metadata_file.exists(), "metadata.json must exist"

    # 内容の整合性確認
    with open(analysis_file, "r", encoding="utf-8") as f:
        analysis_data = json.load(f)
        assert "conversation_overview" in analysis_data
        assert "topics" in analysis_data
        print(f"Verified analysis.json: {len(analysis_data.get('topics', []))} topics extracted.")

    with open(metadata_file, "r", encoding="utf-8") as f:
        meta = json.load(f)
        assert meta["status"] == "COMPLETED"
        assert "execution_time_sec" in meta
        assert "stage3" in meta["execution_time_sec"]
        assert meta.get("stage3_executed") is True
        assert "conversation_type" in meta, "metadata.json must contain conversation_type"
        print(f"Verified metadata.json: type={meta.get('conversation_type')}, times={meta['execution_time_sec']}")

    with open(consistency_report, "r", encoding="utf-8") as f:
        rep = f.read()
        print(f"Verified consistency_report.md preview:\n{rep[:300]}...\n")

    print("Test 3 PASSED!")

    # Test 4: Stage 3 のみ再実行
    print("\n[Test 4] Stage 3 only re-execution from existing draft_summary.md...")
    summary_md.unlink()
    assert not summary_md.exists()

    cmd_stage3 = [PYTHON_BIN, SUMMARY_CLI, "--workspace", str(test_ws), "--stage3-only", "--model", "gemma4:12b"]
    res_stage3 = subprocess.run(cmd_stage3, capture_output=True, text=True)
    assert res_stage3.returncode == 0, f"Stage 3 failed with return code {res_stage3.returncode}"
    assert summary_md.exists(), "summary.md must be regenerated by Stage 3"
    print("Test 4 PASSED: Stage 3 re-execution successful.")
